/opt/conda/lib/python3.11/importlib/__init__.py:126: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.                                                                                                                                                                                                                                                     For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`                                                       with: `from pydantic import BaseModel`                                                                                                      or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. from pydantic.v1 import BaseModel                                                                                                                                                                                                                                                                             return _bootstrap._gcd_import(name[level:], package, level)                                                                               /opt/conda/lib/python3.11/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:               * 'allow_population_by_field_name' has been renamed to 'populate_by_name'                                                                     warnings.warn(message, UserWarning)                                                                                                       [W 2024-09-30 00:05:39.052 ServerApp] jupyter_ai | error adding extension (enabled: True): The `__modify_schema__` method is not supported in Pydantic v2. Use `__get_pydantic_json_schema__` instead in class `SecretStr`.                                                                                                                                                                                                             For further information visit https://errors.pydantic.dev/2.9/u/custom-json-schema                                                          Traceback (most recent call last):                                                                                                            File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 323, in add_extension                                extpkg = ExtensionPackage(name=extension_name, enabled=enabled)                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 187, in __init__                                     self._load_metadata()                                                                                                                     File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 196, in _load_metadata                               self.module, self.metadata = get_metadata(name, logger=self.log)                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                          File "/opt/conda/lib/python3.11/site-packages/jupyter_server/extension/utils.py", line 65, in get_metadata                                    module = importlib.import_module(package_name)                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module                                                            return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/opt/conda/lib/python3.11/site-packages/jupyter_ai/__init__.py", line 3, in <module>
        from jupyter_ai_magics import load_ipython_extension, unload_ipython_extension
      File "/opt/conda/lib/python3.11/site-packages/jupyter_ai_magics/__init__.py", line 4, in <module>
        from .embedding_providers import (
      File "/opt/conda/lib/python3.11/site-packages/jupyter_ai_magics/embedding_providers.py", line 3, in <module>
        from jupyter_ai_magics.providers import (
      File "/opt/conda/lib/python3.11/site-packages/jupyter_ai_magics/providers.py", line 31, in <module>
        from langchain_community.chat_models import QianfanChatEndpoint
      File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
      File "/opt/conda/lib/python3.11/site-packages/langchain_community/chat_models/__init__.py", line 301, in __getattr__                          module = importlib.import_module(_module_lookup[name])                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                    File "/opt/conda/lib/python3.11/importlib/__init__.py", line 126, in import_module                                                            return _bootstrap._gcd_import(name[level:], package, level)                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                               File "/opt/conda/lib/python3.11/site-packages/langchain_community/chat_models/baidu_qianfan_endpoint.py", line 149, in <module>               class QianfanChatEndpoint(BaseChatModel):
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 224, in __new__                                complete_model_class(
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 577, in complete_model_class                   schema = cls.__get_pydantic_core_schema__(cls, handler)                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                   File "/opt/conda/lib/python3.11/site-packages/pydantic/main.py", line 671, in __get_pydantic_core_schema__                                    return handler(source)
               ^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__                          schema = self._handler(source_type)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2088, in inner_handler                            schema = self._generate_schema_inner(obj)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner                    return self.match_type(obj)
               ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type                               return self._match_generic_type(obj, origin)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type                      return self._union_schema(obj)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema                            choices.append(self.generate_schema(arg))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 657, in generate_schema                           metadata_js_function = _extract_get_pydantic_json_schema(obj, schema)                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                     File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2447, in _extract_get_pydantic_json_schema        raise PydanticUserError(
    pydantic.errors.PydanticUserError: The `__modify_schema__` method is not supported in Pydantic v2. Use `__get_pydantic_json_schema__` instead in class `SecretStr`.

    For further information visit https://errors.pydantic.dev/2.9/u/custom-json-schema